title: Log Note
author: author_kyuroject
email: lgj@sds.co.kr
copyright: © 2021 kyuroject
description: > # this means to ignore newlines until "show_excerpts:"
  Kyuroject GitHub Page

show_excerpts: false # set to true to show excerpts on the homepage

lin:
  date_format: "%b %-d, %Y"

  # path to the author avatar image
  avatar_path: assets/images/sr.jpg

  # generate social links
  social_links:
    twitter: jekyllrb
    github:  https://kyuroject.github.io
    medium:  jekyll
    rss: rss
    dribbble: jekyll
    facebook: null
    flickr:   jekyll
    instagram: null
    linkedin: jekyll
    pinterest: null
    youtube_user: null
    youtube_channel: UC8CXR0-null
    telegram: null
    googleplus: null
    keybase: null

theme: lin

plugins:
 - jekyll-feed
 - jekyll-seo-tag

#url: "https://kyuroject.github.io"
#baseurl: "/test"
